/control/verbose 2
/geometry/source polyeth.tg

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree

/geometry/test/run

/vis/open HepRepFile
/vis/drawVolume

/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 0.5 m
/gps/pos/halfy 0.5 m
/gps/pos/centre 0 0 1.5 m

/gps/particle neutron
/gps/energy 3000 keV
/gps/direction 0 0 -1

/vis/scene/add/axes
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 200

/run/beamOn 50

/vis/disable
/analysis/setFileName neut3g.root
/run/verbose 2
/run/printProgress 1000
/run/beamOn 10000